// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imgProto.proto

package com.image.grpc;

public final class ImgProto {
  private ImgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes imageData = 1;</code>
     */
    com.google.protobuf.ByteString getImageData();

    /**
     * <code>string imageName = 2;</code>
     */
    java.lang.String getImageName();
    /**
     * <code>string imageName = 2;</code>
     */
    com.google.protobuf.ByteString
        getImageNameBytes();

    /**
     * <code>repeated string operations = 3;</code>
     */
    java.util.List<java.lang.String>
        getOperationsList();
    /**
     * <code>repeated string operations = 3;</code>
     */
    int getOperationsCount();
    /**
     * <code>repeated string operations = 3;</code>
     */
    java.lang.String getOperations(int index);
    /**
     * <code>repeated string operations = 3;</code>
     */
    com.google.protobuf.ByteString
        getOperationsBytes(int index);
  }
  /**
   * Protobuf type {@code ImageRequest}
   */
  public  static final class ImageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageRequest)
      ImageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageRequest.newBuilder() to construct.
    private ImageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageRequest() {
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      imageName_ = "";
      operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              imageData_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              imageName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                operations_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              operations_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          operations_ = operations_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.image.grpc.ImgProto.internal_static_ImageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.image.grpc.ImgProto.internal_static_ImageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.image.grpc.ImgProto.ImageRequest.class, com.image.grpc.ImgProto.ImageRequest.Builder.class);
    }

    private int bitField0_;
    public static final int IMAGEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString imageData_;
    /**
     * <code>bytes imageData = 1;</code>
     */
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }

    public static final int IMAGENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object imageName_;
    /**
     * <code>string imageName = 2;</code>
     */
    public java.lang.String getImageName() {
      java.lang.Object ref = imageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageName_ = s;
        return s;
      }
    }
    /**
     * <code>string imageName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getImageNameBytes() {
      java.lang.Object ref = imageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList operations_;
    /**
     * <code>repeated string operations = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOperationsList() {
      return operations_;
    }
    /**
     * <code>repeated string operations = 3;</code>
     */
    public int getOperationsCount() {
      return operations_.size();
    }
    /**
     * <code>repeated string operations = 3;</code>
     */
    public java.lang.String getOperations(int index) {
      return operations_.get(index);
    }
    /**
     * <code>repeated string operations = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOperationsBytes(int index) {
      return operations_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!imageData_.isEmpty()) {
        output.writeBytes(1, imageData_);
      }
      if (!getImageNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageName_);
      }
      for (int i = 0; i < operations_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, operations_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!imageData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, imageData_);
      }
      if (!getImageNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < operations_.size(); i++) {
          dataSize += computeStringSizeNoTag(operations_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOperationsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.image.grpc.ImgProto.ImageRequest)) {
        return super.equals(obj);
      }
      com.image.grpc.ImgProto.ImageRequest other = (com.image.grpc.ImgProto.ImageRequest) obj;

      boolean result = true;
      result = result && getImageData()
          .equals(other.getImageData());
      result = result && getImageName()
          .equals(other.getImageName());
      result = result && getOperationsList()
          .equals(other.getOperationsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMAGEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getImageData().hashCode();
      hash = (37 * hash) + IMAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getImageName().hashCode();
      if (getOperationsCount() > 0) {
        hash = (37 * hash) + OPERATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getOperationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.image.grpc.ImgProto.ImageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageRequest)
        com.image.grpc.ImgProto.ImageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.image.grpc.ImgProto.internal_static_ImageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.image.grpc.ImgProto.internal_static_ImageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.image.grpc.ImgProto.ImageRequest.class, com.image.grpc.ImgProto.ImageRequest.Builder.class);
      }

      // Construct using com.image.grpc.ImgProto.ImageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        imageData_ = com.google.protobuf.ByteString.EMPTY;

        imageName_ = "";

        operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.image.grpc.ImgProto.internal_static_ImageRequest_descriptor;
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.ImageRequest getDefaultInstanceForType() {
        return com.image.grpc.ImgProto.ImageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.ImageRequest build() {
        com.image.grpc.ImgProto.ImageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.ImageRequest buildPartial() {
        com.image.grpc.ImgProto.ImageRequest result = new com.image.grpc.ImgProto.ImageRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.imageData_ = imageData_;
        result.imageName_ = imageName_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          operations_ = operations_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.operations_ = operations_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.image.grpc.ImgProto.ImageRequest) {
          return mergeFrom((com.image.grpc.ImgProto.ImageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.image.grpc.ImgProto.ImageRequest other) {
        if (other == com.image.grpc.ImgProto.ImageRequest.getDefaultInstance()) return this;
        if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
          setImageData(other.getImageData());
        }
        if (!other.getImageName().isEmpty()) {
          imageName_ = other.imageName_;
          onChanged();
        }
        if (!other.operations_.isEmpty()) {
          if (operations_.isEmpty()) {
            operations_ = other.operations_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOperationsIsMutable();
            operations_.addAll(other.operations_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.image.grpc.ImgProto.ImageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.image.grpc.ImgProto.ImageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes imageData = 1;</code>
       */
      public com.google.protobuf.ByteString getImageData() {
        return imageData_;
      }
      /**
       * <code>bytes imageData = 1;</code>
       */
      public Builder setImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes imageData = 1;</code>
       */
      public Builder clearImageData() {
        
        imageData_ = getDefaultInstance().getImageData();
        onChanged();
        return this;
      }

      private java.lang.Object imageName_ = "";
      /**
       * <code>string imageName = 2;</code>
       */
      public java.lang.String getImageName() {
        java.lang.Object ref = imageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imageName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getImageNameBytes() {
        java.lang.Object ref = imageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageName = 2;</code>
       */
      public Builder setImageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageName = 2;</code>
       */
      public Builder clearImageName() {
        
        imageName_ = getDefaultInstance().getImageName();
        onChanged();
        return this;
      }
      /**
       * <code>string imageName = 2;</code>
       */
      public Builder setImageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOperationsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          operations_ = new com.google.protobuf.LazyStringArrayList(operations_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOperationsList() {
        return operations_.getUnmodifiableView();
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public int getOperationsCount() {
        return operations_.size();
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public java.lang.String getOperations(int index) {
        return operations_.get(index);
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOperationsBytes(int index) {
        return operations_.getByteString(index);
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public Builder setOperations(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOperationsIsMutable();
        operations_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public Builder addOperations(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOperationsIsMutable();
        operations_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public Builder addAllOperations(
          java.lang.Iterable<java.lang.String> values) {
        ensureOperationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, operations_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public Builder clearOperations() {
        operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string operations = 3;</code>
       */
      public Builder addOperationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOperationsIsMutable();
        operations_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageRequest)
    }

    // @@protoc_insertion_point(class_scope:ImageRequest)
    private static final com.image.grpc.ImgProto.ImageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.image.grpc.ImgProto.ImageRequest();
    }

    public static com.image.grpc.ImgProto.ImageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImageRequest>() {
      @java.lang.Override
      public ImageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.image.grpc.ImgProto.ImageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes mainImageData = 1;</code>
     */
    com.google.protobuf.ByteString getMainImageData();

    /**
     * <code>repeated bytes thumbnailImageData = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getThumbnailImageDataList();
    /**
     * <code>repeated bytes thumbnailImageData = 2;</code>
     */
    int getThumbnailImageDataCount();
    /**
     * <code>repeated bytes thumbnailImageData = 2;</code>
     */
    com.google.protobuf.ByteString getThumbnailImageData(int index);
  }
  /**
   * Protobuf type {@code ImageResponse}
   */
  public  static final class ImageResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageResponse)
      ImageResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageResponse.newBuilder() to construct.
    private ImageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageResponse() {
      mainImageData_ = com.google.protobuf.ByteString.EMPTY;
      thumbnailImageData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImageResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              mainImageData_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                thumbnailImageData_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              thumbnailImageData_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          thumbnailImageData_ = java.util.Collections.unmodifiableList(thumbnailImageData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.image.grpc.ImgProto.internal_static_ImageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.image.grpc.ImgProto.internal_static_ImageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.image.grpc.ImgProto.ImageResponse.class, com.image.grpc.ImgProto.ImageResponse.Builder.class);
    }

    private int bitField0_;
    public static final int MAINIMAGEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString mainImageData_;
    /**
     * <code>bytes mainImageData = 1;</code>
     */
    public com.google.protobuf.ByteString getMainImageData() {
      return mainImageData_;
    }

    public static final int THUMBNAILIMAGEDATA_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> thumbnailImageData_;
    /**
     * <code>repeated bytes thumbnailImageData = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getThumbnailImageDataList() {
      return thumbnailImageData_;
    }
    /**
     * <code>repeated bytes thumbnailImageData = 2;</code>
     */
    public int getThumbnailImageDataCount() {
      return thumbnailImageData_.size();
    }
    /**
     * <code>repeated bytes thumbnailImageData = 2;</code>
     */
    public com.google.protobuf.ByteString getThumbnailImageData(int index) {
      return thumbnailImageData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!mainImageData_.isEmpty()) {
        output.writeBytes(1, mainImageData_);
      }
      for (int i = 0; i < thumbnailImageData_.size(); i++) {
        output.writeBytes(2, thumbnailImageData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!mainImageData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, mainImageData_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < thumbnailImageData_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(thumbnailImageData_.get(i));
        }
        size += dataSize;
        size += 1 * getThumbnailImageDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.image.grpc.ImgProto.ImageResponse)) {
        return super.equals(obj);
      }
      com.image.grpc.ImgProto.ImageResponse other = (com.image.grpc.ImgProto.ImageResponse) obj;

      boolean result = true;
      result = result && getMainImageData()
          .equals(other.getMainImageData());
      result = result && getThumbnailImageDataList()
          .equals(other.getThumbnailImageDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAINIMAGEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getMainImageData().hashCode();
      if (getThumbnailImageDataCount() > 0) {
        hash = (37 * hash) + THUMBNAILIMAGEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getThumbnailImageDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.ImageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.image.grpc.ImgProto.ImageResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageResponse)
        com.image.grpc.ImgProto.ImageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.image.grpc.ImgProto.internal_static_ImageResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.image.grpc.ImgProto.internal_static_ImageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.image.grpc.ImgProto.ImageResponse.class, com.image.grpc.ImgProto.ImageResponse.Builder.class);
      }

      // Construct using com.image.grpc.ImgProto.ImageResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mainImageData_ = com.google.protobuf.ByteString.EMPTY;

        thumbnailImageData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.image.grpc.ImgProto.internal_static_ImageResponse_descriptor;
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.ImageResponse getDefaultInstanceForType() {
        return com.image.grpc.ImgProto.ImageResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.ImageResponse build() {
        com.image.grpc.ImgProto.ImageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.ImageResponse buildPartial() {
        com.image.grpc.ImgProto.ImageResponse result = new com.image.grpc.ImgProto.ImageResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.mainImageData_ = mainImageData_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          thumbnailImageData_ = java.util.Collections.unmodifiableList(thumbnailImageData_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.thumbnailImageData_ = thumbnailImageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.image.grpc.ImgProto.ImageResponse) {
          return mergeFrom((com.image.grpc.ImgProto.ImageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.image.grpc.ImgProto.ImageResponse other) {
        if (other == com.image.grpc.ImgProto.ImageResponse.getDefaultInstance()) return this;
        if (other.getMainImageData() != com.google.protobuf.ByteString.EMPTY) {
          setMainImageData(other.getMainImageData());
        }
        if (!other.thumbnailImageData_.isEmpty()) {
          if (thumbnailImageData_.isEmpty()) {
            thumbnailImageData_ = other.thumbnailImageData_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureThumbnailImageDataIsMutable();
            thumbnailImageData_.addAll(other.thumbnailImageData_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.image.grpc.ImgProto.ImageResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.image.grpc.ImgProto.ImageResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString mainImageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes mainImageData = 1;</code>
       */
      public com.google.protobuf.ByteString getMainImageData() {
        return mainImageData_;
      }
      /**
       * <code>bytes mainImageData = 1;</code>
       */
      public Builder setMainImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainImageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes mainImageData = 1;</code>
       */
      public Builder clearMainImageData() {
        
        mainImageData_ = getDefaultInstance().getMainImageData();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> thumbnailImageData_ = java.util.Collections.emptyList();
      private void ensureThumbnailImageDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          thumbnailImageData_ = new java.util.ArrayList<com.google.protobuf.ByteString>(thumbnailImageData_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getThumbnailImageDataList() {
        return java.util.Collections.unmodifiableList(thumbnailImageData_);
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public int getThumbnailImageDataCount() {
        return thumbnailImageData_.size();
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public com.google.protobuf.ByteString getThumbnailImageData(int index) {
        return thumbnailImageData_.get(index);
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public Builder setThumbnailImageData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureThumbnailImageDataIsMutable();
        thumbnailImageData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public Builder addThumbnailImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureThumbnailImageDataIsMutable();
        thumbnailImageData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public Builder addAllThumbnailImageData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureThumbnailImageDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, thumbnailImageData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes thumbnailImageData = 2;</code>
       */
      public Builder clearThumbnailImageData() {
        thumbnailImageData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageResponse)
    }

    // @@protoc_insertion_point(class_scope:ImageResponse)
    private static final com.image.grpc.ImgProto.ImageResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.image.grpc.ImgProto.ImageResponse();
    }

    public static com.image.grpc.ImgProto.ImageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageResponse>
        PARSER = new com.google.protobuf.AbstractParser<ImageResponse>() {
      @java.lang.Override
      public ImageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImageResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.image.grpc.ImgProto.ImageResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.image.grpc.ImgProto.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.image.grpc.ImgProto.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.image.grpc.ImgProto.Empty.class, com.image.grpc.ImgProto.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.image.grpc.ImgProto.Empty)) {
        return super.equals(obj);
      }
      com.image.grpc.ImgProto.Empty other = (com.image.grpc.ImgProto.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.image.grpc.ImgProto.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.image.grpc.ImgProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.image.grpc.ImgProto.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.image.grpc.ImgProto.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.image.grpc.ImgProto.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.image.grpc.ImgProto.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.image.grpc.ImgProto.Empty.class, com.image.grpc.ImgProto.Empty.Builder.class);
      }

      // Construct using com.image.grpc.ImgProto.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.image.grpc.ImgProto.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.Empty getDefaultInstanceForType() {
        return com.image.grpc.ImgProto.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.Empty build() {
        com.image.grpc.ImgProto.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.image.grpc.ImgProto.Empty buildPartial() {
        com.image.grpc.ImgProto.Empty result = new com.image.grpc.ImgProto.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.image.grpc.ImgProto.Empty) {
          return mergeFrom((com.image.grpc.ImgProto.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.image.grpc.ImgProto.Empty other) {
        if (other == com.image.grpc.ImgProto.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.image.grpc.ImgProto.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.image.grpc.ImgProto.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.image.grpc.ImgProto.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.image.grpc.ImgProto.Empty();
    }

    public static com.image.grpc.ImgProto.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.image.grpc.ImgProto.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016imgProto.proto\"H\n\014ImageRequest\022\021\n\timag" +
      "eData\030\001 \001(\014\022\021\n\timageName\030\002 \001(\t\022\022\n\noperat" +
      "ions\030\003 \003(\t\"B\n\rImageResponse\022\025\n\rmainImage" +
      "Data\030\001 \001(\014\022\032\n\022thumbnailImageData\030\002 \003(\014\"\007" +
      "\n\005Empty24\n\005image\022+\n\nimgProcess\022\r.ImageRe" +
      "quest\032\016.ImageResponseB\020\n\016com.image.grpcb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageRequest_descriptor,
        new java.lang.String[] { "ImageData", "ImageName", "Operations", });
    internal_static_ImageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageResponse_descriptor,
        new java.lang.String[] { "MainImageData", "ThumbnailImageData", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
